### ISSUE TITLE
Implementing the Activity finder function

### ISSUE THREAD

**Issue by theallister** [PeppeL-G/course-material#2]
# Course
Client-Server Communication.

# The problem
When trying to use the SDK function getAllAccounts(), the browser throws an error:

"activity-finder-client.js?7c98:75 Uncaught TypeError: Cannot set property 'getAllAccounts' of undefined
    at Module.eval (activity-finder-client.js?7c98:75)
    at eval (activity-finder-client.js:907)
    at Module../src/activity-finder-client.js (app.js:3492)
    at __webpack_require__ (app.js:727)
    at fn (app.js:101)
    at eval (ListAllAccounts.vue?3504:78)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/ListAllAccounts.vue?vue&type=script&lang=js& (app.js:902)
    at __webpack_require__ (app.js:727)
    at fn (app.js:101)
    at eval (ListAllAccounts.vue?33c1:1)"

When I follow the error codes it takes me to the activity-finder-client.js file. Thus far I have only copied the code from the instructions (and added errors, accounts and isLoading in data())

It seems like the client doesn't communicate with the file in question.

**Comment by theallister** [comment]
Do I need to define a link to the client somewhere else for it to work?
This is what my script looks like: 
`<script>

const client = require('../activity-finder-client')

client.getAllAccounts((errors, accounts) => {
  // errors = array with error codes (empty if everything went OK).
  // accounts = array with all accounts if everything went OK.
  if(errors.length == 0){
    // accounts = [{id: 1, username: "Alice"}, {...}, ...]
  }else{
    // errors = ["errorCode1", "errorCode2", ...]
    // Possible errors codes:
    //  - "networkError": Couldn't connect to the backend.
    //  - "backendError": The backend couldn't execute the request for some reason.
  }
})

export default {
  data() {
    return {
      errors: [],
      accounts: [],
      isLoading: true
    }
  }
}

</script>`

**Comment by PeppeL-G** [comment]
It appears to be complaining about line 75 in the SDK, which is the following line of code:

```js
module.exports.getAllAccounts = async function(callback){
```

According to the error message `Cannot set property 'getAllAccounts' of undefined`, `module.exports` is `undefined`, but it shouldn't be that.

Can you show me line 75 as you have it in your `activity-finder-client.js` file?

**Comment by PeppeL-G** [comment]
Or have you somewhere in your code tried to import `activity-finder-client.js` as an ECMAScript module? I.e., have you somewhere in your code written something like this:

```js
import client from '../activity-finder-client'
```

? Because that won't work and give you an error like this one. The file `activity-finder-client.js` is exporting values as described by the CommonJS specification, so you must import those values as described by the CommonJS specification (i.e. use the `require()` function instead of the import statement).

**Comment by theallister** [comment]
module.exports.getAllAccounts = async function(callback){
 is what's on line 75!

**Comment by PeppeL-G** [comment]
And you don't have `import client from '../activity-finder-client'` anywhere in your code? Simply search for `activity-finder-client` in your source code to find all places where you have included it.

If you haven't imported the file as an ECMAscript module, email a ZIP file with your source code (without the `node_modules` folder) to Peter.Larsson-Green@ju.se and I'll take a look at it.

**Comment by PeppeL-G** [comment]
I received your code, and guess what, your code runs fine on my computers (tried both Mac and Windows) :)

Can you show me the content of your `package.json` file and what the following two commands executed in a terminal gives you:

1. `npm --version`
2. `node --version`

Don't know if that will give any hint about the problem, but if it doesn't we can take a look at it after the tutorial tomorrow. It seems to be a problem specific to your computer somehow, and I don't know what that "specific" thing is.

**Comment by PeppeL-G** [comment]
@theallister I guess you attached `package.json` to the email, but it isn't shown here.

**Comment by PeppeL-G** [comment]
The problem was a babel package that seem to have transpiled the code so `module.exports` didn't work as described by CommonJS.
