### ISSUE TITLE
Blank fragment when replacing a fragment inside a viewpager

### ISSUE THREAD

**Issue by almu1800** [PeppeL-G/course-material#3]
# Course
android development

# The problem
I Created a  navigation bar using viewPager and fragments, navigation bar sounds working as it should!
```kt
        navigationTabLayout=findViewById(R.id.navigationTabId)
        mainViewPager=findViewById(R.id.mainViewPagerId)
        viewPagerAdapter= ViewPagerAdapter(supportFragmentManager)
        // here we need to add fragment to adabter
        viewPagerAdapter.addFragment(StartFragment(),"Home")
        viewPagerAdapter.addFragment(ViewAdFragment(),"Create Ad")  // CreateAdFragment should be added here
        viewPagerAdapter.addFragment(ViewAdFragment(),"Messages")   //   MessagesFragment should be added here
        viewPagerAdapter.addFragment(ViewAdFragment(),"Account")    // accountFragment should be added here
        // connect the adapter to the viewPager
        mainViewPager.adapter=viewPagerAdapter
        // connect the viewPager to the tabLayout
       navigationTabLayout.setupWithViewPager(mainViewPager)
```

In startFragment, I have a listView and when I click on an list item I want startFragment to be replaced with another fragment, this is the code I am using:

```kt
        booksListView.setOnItemClickListener { parent, view, position, id ->
            // start ViewAdFragment!!
            val fragmentManager=activity!!.supportFragmentManager
            val transaction=fragmentManager.beginTransaction()
            val ins=transaction.replace(R.id.mainViewPagerId,ViewAdFragment.newInstance(books[position].id))
            transaction.addToBackStack(null)
            transaction.commit()

            //viewPagerAdapter.notifyDataSetChanged()
        }
```
the problem is that I am getting a blank viewPager when clicking on any Item in the list
# The question(s)
How should I do to replace startFragment with ViewAdFragment properly?

**Comment by PeppeL-G** [comment]
I don't know how your `viewPagerAdapter` works. I recommend you to create a new activity based on the template `Tabbed Activity`, and you'll see how to set up a `TabLayout` with a `ViewPager`, but maybe you use an adapter from a library, and then maybe you use it correct as it is.

I don't know how to use a `ViewPager` properly to 100%, but to me your solution sounds a bit weird. I think the fragments that should be shown in the `ViewPager` all should be part of and created by your `ViewPagerAdapter`. To me it sounds wrong to tell the `ViewPager` to show a fragment not part of the adapter.

The solution I suggest is that your `StartFragment` just contains a `FrameLayout` in which you dynamically can change which fragment it displays. Initially it displays the `ListAllItemsFragment` (or whatever you call it), and when the user clicks on one of the items, you tell the `FrameLayout` to display the `ViewItemFragment` (or whatever you call it) instead.

Do you follow?

**Comment by almu1800** [comment]
Yes, I do. I will try a create a frameLayout in my StartFragment.
thanks
