### ISSUE TITLE
need update link 

### ISSUE THREAD

**Issue by epogrebnyak** [PeppeL-G/course-material#30]
At https://peppel-g.github.io/course-material/lectures/python-object-oriented-programming/#recommended-reading

the working link to _How to Think Like a Computer Scientist: Interactive Edition_  to should be 

 https://runestone.academy/ns/books/published//thinkcspy/index.html

**Comment by PeppeL-G** [comment]
Many thanks! Changes will be shown when I upload the next version to GitHub Pages.
