### ISSUE TITLE
data not rendering 

### ISSUE THREAD

**Issue by abch21li** [PeppeL-G/course-material#41]
# Course - 
Web Development 

# The problem - 
Data is being stored in my database, but it isn't being rendered properly back to the reviews page. 
When I submit the form, only the id and basic template show up, but not what I entered into the form. 

# Failed attempt - 
I've tried adjusting the name of the model called in the app, but somewhere I'm not referencing something properly. When I run the current code, the data is entered into my database, and a new item is produced on my reviews page with the empty fields and the proper id, but not the inputted information (review and name) 

# The question(s)

1) What am doing wrong? Have I not properly referenced the model? Or perhaps with the naming? 
2) Have I made a mistake with the "Render" portion of the /reviews post request?

<img width="952" alt="Screen Shot 2022-09-21 at 11 03 04 AM" src="https://user-images.githubusercontent.com/93584687/191463217-60277fb2-9cf6-4d6d-a542-10ff769529a0.png">
<img width="470" alt="Screen Shot 2022-09-21 at 11 03 24 AM" src="https://user-images.githubusercontent.com/93584687/191463225-497a3f83-5a79-449a-9a25-e7b7f150707a.png">
<img width="475" alt="Screen Shot 2022-09-21 at 11 03 35 AM" src="https://user-images.githubusercontent.com/93584687/191463233-a4aded68-e07e-45c6-aefe-e3f04c1c59ab.png">
<img width="473" alt="Screen Shot 2022-09-21 at 11 03 53 AM" src="https://user-images.githubusercontent.com/93584687/191463238-140ede3a-b45a-45eb-b52f-374286f6bafe.png">

**Comment by PeppeL-G** [comment]
Hi!

In the database, you call the fields for `text` and `name`. When you retrieve reviews from the database, you will get objects like `{id: 1, name: "SOMETHING", text: "SOMETHING"}`. So in your handlebars code, you must use `{{name}}` and `{{text}}`. Currently you are using `{{reviewtext}}` and `{{artistname}}`, and that's why it doesn't work.

**Comment by abch21li** [comment]
Ahhh I see now. Thank you!
________________________________
