### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by semikandiyoti** [PeppeL-G/course-material#45]
# Course
Client-Server Communication

# The problem
When i try to create a task (In my case a new booking), when I click the button, I recieve this error.
## Example 1

https://prnt.sc/CbCdZwTfeho8, https://prnt.sc/NAqfFy-HmVvK

After that I also got 403 error code; https://prnt.sc/ih6ag6La2RkD https://prnt.sc/qsRhVavKMUOP

I think it doesnt like my fetch address: fetch("http://localhost:8080/bookings", {
                method: "POST",

Let me know if you can help somehow

Thanks

**Comment by PeppeL-G** [comment]
The 403 error I can't explain (do you ever send that back yourself in your backend code?), but the 500 error is probably easier to figure out. What does the code look like in the backend that handles that request (the `app.post('/bookings', function(request, response){ ... })` part)?

**Comment by semikandiyoti** [comment]
Just like this:

app.post('/bookings', function(request, response){

    const city = request.body.city
    const date = request.body.date
    const time = request.body.time
    const reason = request.body.reason


    const errorCodes = []


    if(0 < errorCodes.length){
        response.status(400).json(errorCodes)
    }else{

        const query = "INSERT INTO bookings (city, date, time, reason)
VALUES (?, ?, ?, ?)"
        const values = [city, date, time, reason]

        db.run(query, values, function(error){
            if(error){
                response.status(500).end()
            }else{
                response.status(201).end()
            }
        })

**Comment by PeppeL-G** [comment]
Then most likely you get an error from the database. Try logging that error too see what it complains about.

```js
            if(error){
                console.log(error) // Add this line of code!
                response.status(500).end()
            }else{
```

Then restart the backend, send the request again from the frontend, and then see in the terminal that started the backend what the logged error was.

**Comment by semikandiyoti** [comment]
OMG! thank you so much!! I had a stupid typo in my backend that was the problem, found out in the log book...

**Comment by PeppeL-G** [comment]
No problem.
