### ISSUE TITLE
Cannot find the page for common mistakes on the report

### ISSUE THREAD

**Issue by davidmansourian** [PeppeL-G/course-material#47]
# Course
Web Development Fundamentals 2022

# The problem
Cannot find the page for common mistakes on the report

# The question(s)
Where can I find the page that specifies common mistakes on the report?

**Comment by davidmansourian** [comment]
i found it

**Comment by PeppeL-G** [comment]
Hi!

The page mentioning the common report mistakes students often do was something I used last year, and it was not meant to be used this year (this year the idea is that Susanne teaches you how to write reports), so if you find a link to it, please let me know, and I'll remove it.

// Peter L-G

**Comment by davidmansourian** [comment]
I just found it in your git directory. But good to know, I wont use it then!
