### ISSUE TITLE
Log out user

### ISSUE THREAD

**Issue by tuvapersson** [PeppeL-G/course-material#48]
# Course
Client-Server Communication.

# The problem
We are trying to log out the user, and we do this by using props user Object and setting isLoggedIn to false, and accessToken to null. For some reason the user prop is not recognized – when we console.log the user it says undefined. We made sure that everything is correctly spelled, so that should not be the problem. Here is our code:
 
<img width="1096" alt="Screenshot 2022-10-14 at 11 19 18" src="https://user-images.githubusercontent.com/80885269/195811082-9d93d9d3-ea06-43f6-b225-72cde2dbb9fb.png">
<img width="488" alt="Screenshot 2022-10-14 at 11 21 17" src="https://user-images.githubusercontent.com/80885269/195811551-19833664-ba92-45ec-a141-c7e396e7b19b.png">

**Comment by PeppeL-G** [comment]
When you use `<RouterView :user="user"></RouterView` in `App.vue`, you only pass along the user object as a props to the `.vue` files in the `views` folder.

I'm guessing you are using `<DashboardHeader></DashboardHeader>` in `App.vue`. It must be `<DashboardHeader :user="user"></DashboardHeader>` to pass along the user object as a props to also that one.

**Comment by paulinewahle** [comment]
Easy fix. Thank you!
