### ISSUE TITLE
Router replace

### ISSUE THREAD

**Issue by paulinewahle** [PeppeL-G/course-material#50]
# Course
Client-Server Communication.

# The problem
We would like to be directed to the "home" page once the user signed in, instead of staying on the sign in page again. We thought we would do that with router.replace, but once you come to the home page (where all the user's own projects should show), it doesn't recognise the id of the account that just signed in, even though we state it right before the router.replace code. It is like the replace is happening so fast that it doesn't have the time to read out what the user id is first, and therefore can't display the projects.

This problem doesn't occur at all if we delete the router.replace.

# Failed attempt

<img width="711" alt="Screenshot 2022-10-17 at 15 06 19" src="https://user-images.githubusercontent.com/80485598/196184799-6b27cc16-2147-43a2-941d-a7f7ade02cd3.png">
<img width="488" alt="Screenshot 2022-10-17 at 15 07 28" src="https://user-images.githubusercontent.com/80485598/196185024-73769abe-57ba-4643-98ab-9f3caf344801.png">

**Comment by PeppeL-G** [comment]
>It is like the replace is happening so fast that it doesn't have the time to read out what the user id is first, and therefore can't display the projects.

Yea, something like that; you call `response.json()` to parse the body in JSON format, and that's an asynchronous operation, meaning that the web browser will parse it in the background, and the rest of your code continues to run. So you call `router.replace()` before the body has been parsed (before lines 42-55 has run).

The solution is to move the `router.replace()` line so it runs after you have assigned `this.user` it correct values (move it to, for example, line 53).

**Comment by PeppeL-G** [comment]
And usually one writes `this.$router` instead of just `router`, so maybe that's something that needs to be fixed too.
