### ISSUE TITLE
Flexible props?

### ISSUE THREAD

**Issue by paulinewahle** [PeppeL-G/course-material#53]
# Course
Client-Server Communication.

# The problem
We got introduced to props on the example of :user. Can we modify the props concept in a way that it can be used flexible for multiple things simultaneously? Here is our idea:

## Material
When creating a new project the creator can choose a color it should be displayed in. Implemented with :style.
This is working fine but for general understanding: 
<img width="1139" alt="Screenshot 2022-10-22 at 14 41 51" src="https://user-images.githubusercontent.com/80485598/197339570-a13e2438-2662-46c9-becc-4ba1dbaa267b.png">

<img width="1139" alt="Screenshot 2022-10-22 at 14 42 12" src="https://user-images.githubusercontent.com/80485598/197339574-27e78fec-3552-4854-8f8a-4e4eae95cc6c.png"> 

<img width="1139" alt="Screenshot 2022-10-22 at 14 42 24" src="https://user-images.githubusercontent.com/80485598/197339586-33aac758-e127-4bc7-b828-c75165cc7c71.png">

<img width="1139" alt="Screenshot 2022-10-22 at 14 10 25" src="https://user-images.githubusercontent.com/80485598/197339445-0f469c26-1dab-45f4-b8e1-f851f253a07d.png">

And of course this should be remembered and shown in the View of all Projects. For this we redefine the value in the prop project in App.vue, since this is our only understanding of how to pass it along. 
<img width="1139" alt="Screenshot 2022-10-22 at 14 46 55" src="https://user-images.githubusercontent.com/80485598/197339731-d6bc22c6-624a-4679-8a76-d49531f30fb9.png">

<img width="1139" alt="Screenshot 2022-10-22 at 14 11 06" src="https://user-images.githubusercontent.com/80485598/197339715-57aab4cd-f496-4798-a7bf-e8cabe1e935b.png">

The problem with this is, logically, whenever a new project is being created and a new color chosen/reassigned it's applied to all projects connected to the prop.
<img width="1139" alt="Screenshot 2022-10-22 at 14 11 40" src="https://user-images.githubusercontent.com/80485598/197339767-8349b09f-a8c4-43d4-9c88-65add40481f1.png">
<img width="1139" alt="Screenshot 2022-10-22 at 14 11 46" src="https://user-images.githubusercontent.com/80485598/197339773-da73b662-13d7-4df3-a44a-7d530627135a.png">

#Question 
How can we assign a prop to the projects id?

**Comment by PeppeL-G** [comment]
Hi!

You want different projects to be able to have different colors? Then each project should have a `color` property, in which you store the color the project should have, in the same way that each project has a `title`, etc. As far as I understand, you should not need to use a props at all.

// Peter L-G
